# Generated by Django 2.1.7 on 2019-04-15 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('potassium', models.FloatField(max_length=5)),
                ('sodium', models.FloatField(max_length=5)),
                ('blood_pressure', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
