# Generated by Django 2.1.7 on 2019-04-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sodium',
        ),
    ]
