# Generated by Django 2.1.7 on 2019-04-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_auto_20190420_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('potassium', models.FloatField()),
                ('sodium', models.FloatField()),
                ('blood_pressure', models.CharField(choices=[('HIGH', 'high'), ('NORMAL', 'normal'), ('LOW', 'low')], max_length=6)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.Patient')),
            ],
        ),
    ]
