# Generated by Django 2.1.7 on 2019-04-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_patientdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
