# Generated by Django 2.1.7 on 2019-04-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_auto_20190421_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdetail',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
