# Generated by Django 2.1.7 on 2019-04-21 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_auto_20190421_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
