# Generated by Django 2.1.7 on 2019-04-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0007_patientdetail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='disease_identified',
            field=models.CharField(choices=[('HIV', 'HIV'), ('Malaria', 'malaria'), ('Tuberculosis', 'tuberculosis'), ('Diabetes 1', 'diabetes type 1'), ('Diabetes 2', 'diabetes type 2')], default='Malaria', max_length=12),
        ),
    ]
