# Generated by Django 2.1.7 on 2019-04-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0008_patientdetail_disease_identified'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='medicine',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
