# Generated by Django 2.1.7 on 2019-04-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0011_auto_20190426_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='alcoholic',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='breast_feeding',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='diabetes',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='disease_identified',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='eye_disease',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='kidney_disease',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='liver_disease',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='pregnant',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1),
        ),
    ]
