# Generated by Django 2.1.7 on 2019-04-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0013_auto_20190426_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='disease_identified',
            field=models.CharField(choices=[('Malaria', 'malaria'), ('Tuberculosis', 'tuberculosis')], max_length=20),
        ),
    ]
