# Generated by Django 2.1.7 on 2019-05-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0014_auto_20190426_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='medicine',
            field=models.CharField(blank=True, choices=[('Doxycycline', 'doxycycline'), ('Lariam', 'lariam'), ('Malarone', 'malarone'), ('Rifater', 'rifater'), ('Ethambutol', 'ethambutol'), ('Isoniazid', 'isoniazid')], max_length=20),
        ),
    ]
