# Generated by Django 2.1.7 on 2019-05-20 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0015_auto_20190503_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
    ]
